#!usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when recieving a SIGTERM signal# Displays Y U no love me?! when recieving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itsef
# when recievig a SIGQUIT or SIGTERM signal


echo "$$" > /var/run/myscript.pid

termfunc() {
	rm /var/run/myscript.pid
	exit
}


while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && termfunc' SIGTERM
	trap 'termfunc' SIGQUIT
done
