#!/usr/bin/env bash
# This script creates the file /var/run/holbertonscript.pid containing it's PID
#Displays To infinity and beyond indefinitely
# Displays I hate the kill command when rexieving a SIGTERM signal
# Displays Y U no love e?! when recieving a SIGINT signal
# Deletes the file /var/run/holbertonscript and termninate itself when recieving a SIGQUIT or SIGTERM signal

function love() {
    rm /var/run/holbertonscript.pid
    exit
}

trap "echo I hate the kill command;love" SIGTERM
trap "echo Y U no love me?!;love" SIGINT

echo $$ >> /var/run/holbertonscript.pid
while [ true ]; do
    echo To infinity and beyond;
done
